<a href="https://colab.research.google.com/github/MrSantoshkumar/PYTHON-IITM/blob/main/Week_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## L5.1| Intoduction to Functions

In [ ]:
def add(a,b):
   ans=a+b
   print(ans)

In [ ]:
add(1,6)

7


In [ ]:
add(10,72)

82


In [ ]:
def sub(a,b):
  ans=a-b
  print(ans)


In [ ]:
sub(10,8)

2


In [ ]:
add(2,3)

5


In [ ]:
def discount(cost,d):
  ans=cost-(cost*(d/100))
  print(ans)


In [ ]:
discount(100,8)

92.0


In [ ]:
discount(100,10)

90.0


In [ ]:
add(17,5)+sub(100,3)+discount(1500,5)

22
97


TypeError: unsupported operand type(s) for +: 'NoneType' and 'NoneType'

In [ ]:
(17+5)+(100-3)

119

In [ ]:
def add(a,b):
  ans=a+b
  return ans

In [ ]:
a=3
b=19
print(add(a,b))

22


In [ ]:
a=2
b=15
ans=add(a,b)+10
print(ans)

27


In [ ]:
def add(a,b):
   ans=a+b
   print(ans)

In [ ]:
a=2
b=15
ans=add(a,b)+10
print(ans)

17


TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

In [ ]:
def discount(cost,d):
  ans=cost-(cost*(d/100))
  return(ans)

In [ ]:
print("Enter the cost")
c=int(input())
print("Enter the discount")
disc=int(input())
print("The finall discount is :",discount(c,disc))

Enter the cost
100
Enter the discount
20
The finall discount is : 80.0


In [ ]:

print("The final discount is :",discount(x,y))

NameError: name 'x' is not defined

## **L5.2|More Example on Functions**

#Let us write a few functions on lists.

In [ ]:
def first_element(l):
  return l[0]

In [ ]:
x=[1,2,3]
first_element(x)

1

In [ ]:
def second_element(l):
    return l[1]

In [ ]:
second_element(x)

2

In [ ]:
def list_min(l):
    mini=l[0]
    for i in range(len(l)):
      if(l[i]<mini):
        mini=l[i]
    return mini

In [ ]:
def list_maxi(l):
    maxi=l[0]
    for i in range(len(l)):
       if(l[i]>maxi):
          maxi=l[i]
    return maxi

In [ ]:
def list_appendbefore(l,z):
  newl=[]
  for i in range(len(z)):
      newl.append(z[i])
  for i in range(len(l)):
      newl.append(l[i])
  return newl


In [ ]:
def list_appendend(l,z):
  newl=[]
  for i in range(len(l)):
      newl.append(l[i])
  for i in range(len(z)):
      newl.append(z[i])
  return newl


In [ ]:
def list_average(l):
    sum=0
    for i in range(len(l)):
      sum=sum+l[i]
    ans=sum/len(l)
    return ans

In [ ]:
l=[1,2,3,4,5,-10,6,4,10000000]
print(list_min(l))
print(list_maxi(l))
z=[10,20,30,40,50]
print(list_appendbefore(l,z))
print(list_appendend(l,z))
print(list_average(l))

-10
10000000
[10, 20, 30, 40, 50, 1, 2, 3, 4, 5, -10, 6, 4, 10000000]
[1, 2, 3, 4, 5, -10, 6, 4, 10000000, 10, 20, 30, 40, 50]
1111112.7777777778


In [ ]:
list_maxi([1,-1,10,6,-2])

10

# L5.3|Sorting using Function

#find out the minimum most element in the list.
#append to a new list x.
#remove the minimun form the original list.

In [ ]:
#find out the minimum most element in the list l
def min_list(l):
  mini=l[0]
  for i in range(len(l)):
       if(l[i]<mini):
         mini=l[i]
  return mini

def obvious_sort1(l):
    x=[]
    while(len(l)>0):
        mini=min_list(l)
        x.append(mini)
        l.remove(mini)
    return x


# we just learnt that breaking our problem in to smaller modules and solving them makes it easy on our mind (ability to break a program in to small chanks )




def obvious_sort(l):

   x=[]
   while(len(l)>0):
       mini=l[0]
       for i in range(len(l)):
         if(l[i]<mini):
           mini=l[i]
       x.append(mini)
       l.remove(mini)
   return x


In [ ]:
l=[90,23,97,88,5,1]
print(obvious_sort1(l))

[1, 5, 23, 88, 90, 97]


**L5.4|Matrix Multiplication using Functions**(*Functional approch programming* )

In [ ]:
# initialise  C to zero
# I need to consider two matrices A and B
# I need to find the dot product of two lists
# I need to pick ith row and jth column in a matrix .

def initialize_mat(dim):
# Code verified , works perfectly fine on the test cases
  C=[]
  for i in range(dim):
    C.append([])
  for i in range(dim):
      for j in range(dim):
       C[i].append(0)
  return C
print(initialize_mat(4))



[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]


Dot product

In [ ]:
def dot_product(u,v):
  dim=len(u)
  ans=0
  for i in range(dim):
      ans=ans+(u[i]*v[i])
  return ans

def row(M,i):
    dim=len(M)
    l=[]
    for k in range(dim):
        l.append(M[i][k])
    return l

def column(M,j):
    dim=len(M)
    l=[]
    for k in range(dim):
        l.append(M[k][j])
    return l

def mat_mul(A,B):
    dim=len(A)     # len(A)=len(B)
    C=initialize_mat(dim)
    for i in range(dim):
        for j in range(dim):
            #C[i][j]=ith row of A * jth col of B
            C[i][j]=dot_product(row(A,i),column(B,j))
    return C


In [ ]:
x=[1,2,3]
y=[7,1,2]
dot_product(x,y)

15

In [ ]:
column(A,0)

[1, 4, 7]

In [ ]:
column(A,1)

[2, 5, 8]

In [ ]:
column(A,2)

[3, 6, 9]

In [ ]:
A=[[1,2,3],[4,5,6],[7,8,9]]
row(A,0)

[7, 8, 9]

In [ ]:
row(A,1)

[4, 5, 6]

In [ ]:
row(A,2)

[7, 8, 9]

In [ ]:
# (1*7)+(2*1)+(3*2)
dot_product([1,2,3],[7,1,2])

15

In [ ]:
C=[[0,0,0],[0,0,0],[0,0,0]]
print(C)

[[0, 0, 0], [0, 0, 0], [0, 0, 0]]


In [ ]:
C=[[],[],[]]
C[0].append([0,0,0])
print(C)

[[[0, 0, 0]], [], []]


In [ ]:
A

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
B=[[1,2,1],[3,1,7],[6,2,3]]

In [ ]:
mat_mul(A,B)

[[25, 10, 24], [55, 25, 57], [85, 40, 90]]

In [ ]:
import numpy
A=numpy.mat(A)
B=numpy.mat(B)
C=A*B
print(C)

[[25 10 24]
 [55 25 57]
 [85 40 90]]


# L**5.5|Theortical Introduction to Recursion**

# L5.6 | Recursion Illustration

In [ ]:
n=1000000000
ans=0
for i in range(n):
  ans=ans+(i+1)
print(ans)

500000000500000000


In [ ]:
def sum(n):
  ans=0
  for i in range(n):
      ans = ans+(i+1)
  return ans

In [ ]:
sum(100)

5050

# Recursion in Python

In [ ]:
def sum(n):
  if(n==1):
      return 1
  else:
    return n+sum(n-1)
    #python lets you call the same function within the function.

In [ ]:
print(sum(100))

5050


In [ ]:
# compute compound interest by assuming the interest to be 10%
def comp(p,n):
    if(n==1):
      return p*(1.1)
    else:
      return (comp(p,n-1))*1.1

In [ ]:
print(comp(10000,10))

25937.424601000024


In [ ]:
def fact(n):
   if(n==1):
      return 1
   else:
       return (fact(n-1))*n

In [ ]:
fact(100)

93326215443944152681699238856266700490715968264381621468592963895217599993229915608941463976156518286253697920827223758251185210916864000000000000000000000000

# **L5.7|Type of Function Arguments**

In [ ]:
def add(a,b,c):
    return (a+b-c)
print(add(20,30,40))

10


In [ ]:
print(add(a=20,b=30,c=40))

10


In [ ]:
def add(c,a=20,b=30):
  return(a+b-c)

In [ ]:
print(add(40))
print(add(40,10))
print(add(40,10,50))
print(add(40,b=10,a=50))

10
0
20
20


# L 5.8|Scope of Variables

In [ ]:
def myFunction1(x):
  global x
  x=x*2
  print("Value of x in function 1 ",x)

def myFunction2(x):
  global x
  x=x*3
  print("Value of x in function 2",x)

x=5
print("Value of x before function call",x)
myFunction1(x)
myFunction2(x)
print("Value of x after fuction call",x)

SyntaxError: name 'x' is parameter and global (<ipython-input-10-31919a929199>, line 2)

# L5.9|Type of Functions

In [ ]:
#Inbuild function
print(), input(),len()
# Library function
math.log(), math.sqrt() , math.random(), random.randrange() , calender() ,calendar.month()

#Srting methods (functions)
upper(),  lower(),  strip(), count(),  index(), replace()

In [ ]:
#uder defined functions
def square(x):
  sqr=x**2
  return sqr

In [ ]:
print(square(5))

25


# L5.10|Tutorial on functions

Problem 1: Write a python code using functions which calculates the number of upper case letters,lower case letters, total number of characters and number of words

In [ ]:
def upper(s):
  upper=0
  for c in s:
      if(c.isupper()):
          upper +=1
  return(upper)

def lower(s):
    lower=0
    for c in s:
        if(c.islower()):
             lower+=1
    return (lower)

def characters(s):
    chars=0
    for c in s:
        chars +=1
    return (chars)

def words(s):
    words = 1
    for c in s:
        if(c==' '):
            words += 1
    return(words)

sentence=input("Enter the sentence:")
uLetters = upper(sentence)
print(f'\nTotal number of upper case characters:{uLetters}')
lLetters=lower(sentence)
print(f'\nTotal number of lower case characters:{lLetters}')
chars=characters(sentence)
print(f'

f\nTotal number of characters:{chars}')
words=words(sentence)
print(f'\nTotal number of words:{words}')


Enter the sentence:Functions Could Have Multiple Returns Statements,But The Moment The First Return Is Executed,Control Exits 

Total number of upper case characters:16

Total number of lower case characters:75

Total number of characters:107

Total number of words:15


Problem 2:Write a Python code using functions to calculate area and perimeter of circle and rectangle

In [ ]:
''' Approch 1:Standard code'''
PI = 22/7
def circle_area(r):
     return(PI*r*r)

def circle_perimeter(r):
     return(2*PI*r)

def rectangle_area(l,b):
     return (l*b)

def rectangle_perimeter(l,b):
     return(2*(l+b))

r=float(input('\nEnter the radius of the circle:'))
cArea=circle_area(r)
print(f'\nArea of circle with radius {r} = {cArea} as sq.units')
cPerimeter=circle_perimeter(r)
print(f'\nPerimeter of circle with radius {r} = {cPerimeter}units')
l=float(input('\nEnter the length of the rectangle:'))
b=float(input('\nEnter the breadth of the rectangle:'))
rArea = rectangle_area(l,b)
print(f'\nArea of rectangle with  length {l} and breadth {b}={rArea} sq units ')
rPerimeter = rectangle_area(l,b)
print(f'\nPerimeter of rectangle with length {l} and breath {b} = rPerimeter')


Enter the radius of the circle:7

Area of circle with radius 7.0 = 154.0 as sq.units

Perimeter of circle with radius 7.0 = 44.0units

Enter the length of the rectangle:7

Enter the breadth of the rectangle:12

Area of rectangle with  length 7.0 and breadth 12.0=84.0 sq units 

Perimeter of rectangle with length 7.0 and breath 12.0 = rPerimeter


Problem 3: Write a Python code using functions which checks whether the input coordinates form a triangle or not

In [ ]:
def distance(xi,yi,xj,yj):
   return(((xj-xi)**2) + ((yj-yi)**2))**0.5

x1=float(input('Enter x coordinate of 1st point:'))
y1=float(input('Enter y coordinate of 1st point:'))
x2=float(input('Enter x coordinate of 2nd point:'))
y2=float(input('Enter y coordinate of 2nd point:'))
x3=float(input('Enter x coordinate of 3rd point:'))
y3=float(input('Enter y coordinate of 3rd point:'))
d1 = distance(x1,y1,x2,y2)
print(f'\nDistance between points ({x1},{y1}) and ({x2},{y2}={d1})')
d2 = distance(x2,y2,x3,y3)
print(f'\nDistance between points ({x2},{y2}) and ({x3},{y3})={d2} ')
d3 = distance(x3,y3,x1,y1)
print(f'\nDistance between points ({x3},{y3}) and ({x1},{y1})= {d3}')

if(d1>d2):
    if(d1>d3):
       isTriangle(d1,d2,d3)
    else:
      isTriangle(d3,d1,d2)
elif(d2 > d3):
   isTriangle(d2,d1,d3)
else:
    isTriangle(d3 ,d1,d2)


Enter x coordinate of 1st point:1
Enter y coordinate of 1st point:2
Enter x coordinate of 2nd point:3
Enter y coordinate of 2nd point:4
Enter x coordinate of 3rd point:5
Enter y coordinate of 3rd point:6

Distance between points (1.0,2.0) and (3.0,4.0=2.8284271247461903)

Distance between points (3.0,4.0) and (5.0,6.0)=2.8284271247461903 

Distance between points (5.0,6.0) and (1.0,2.0)= 5.656854249492381


NameError: name 'isTriangle' is not defined

In [ ]:
import math

def slope(xi,yi,xj,yj):
     if(xi==xj):
         return(math.inf)
     else:
        return((yj-yi)/(xj-xi))



x1=float(input('Enter x coordinate of 1st point:'))
y1=float(input('Enter y coordinate of 1st point:'))
x2=float(input('Enter x coordinate of 2nd point:'))
y2=float(input('Enter y coordinate of 2nd point:'))
x3=float(input('Enter x coordinate of 3rd point:'))
y3=float(input('Enter y coordinate of 3rd point:'))
s1=slope(x1,y1,x2,y2)
print(f'\nSlope of the line connecting points ({x1},{y1}) and ({x2},{y2}={d1})')
s2 = slope(x2,y2,x3,y3)
print(f'\nSlope of the line connecting points ({x2},{y2}) and ({x3},{y3})={d2} ')
s3 = slope(x3,y3,x1,y1)
print(f'\nSlope of the line connecting6 points ({x3},{y3}) and ({x1},{y1})= {d3}')

if(s1!=s2):
   print('\nTriangle')
else:
   print('\nNot a triangle')



Enter x coordinate of 1st point:0
Enter y coordinate of 1st point:0
Enter x coordinate of 2nd point:0
Enter y coordinate of 2nd point:1
Enter x coordinate of 3rd point:1
Enter y coordinate of 3rd point:0

Slope of the line connecting points (0.0,0.0) and (0.0,1.0=2.8284271247461903)

Slope of the line connecting points (0.0,1.0) and (1.0,0.0)=2.8284271247461903 

Slope of the line connecting6 points (1.0,0.0) and (0.0,0.0)= 5.656854249492381

Triangle
