<a href="https://colab.research.google.com/github/MrSantoshkumar/PYTHON-IITM/blob/main/WEEK_4_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

L4.2 Warmup with Lists

In [ ]:
l = [1,7,4,2,100]
print(l)


[1, 7, 4, 2, 100]


In [ ]:
l.append(1739)
print(l)

[1, 7, 4, 2, 100, 1739]


In [ ]:
l.append(2)
print(l)

[1, 7, 4, 2, 100, 1739, 2]


In [ ]:
l.remove(1)
print(l)

[7, 4, 2, 100, 1739, 2]


In [ ]:
l.remove(2)
print(l)

[7, 4, 100, 1739, 2]


In [ ]:
l.remove(2)
print(l)

[7, 4, 100, 1739]


In [ ]:
l = []
l.append(2)
l.append(3)
l.append(5)
print(l)

[2, 3, 5]


In [ ]:
x = []
x.append(l)
print(x)

[[2, 3, 5]]


In [ ]:
m=[10,20,30]
x.append(m)
print(x)

[[2, 3, 5], [10, 20, 30]]


In [ ]:
t=[]
t.append(x)
print(t)

[[[2, 3, 5], [10, 20, 30]]]


In [ ]:
t.append([100,101,102])
print(t)

[[[2, 3, 5], [10, 20, 30]], [100, 101, 102]]


In [ ]:
print(t[0])

[[2, 3, 5], [10, 20, 30]]


In [ ]:
print(t[1])

[100, 101, 102]


In [ ]:
M=[]
M.append([1,2,3])
M.append([4,5,6])
M.append([7,8,9])
print(M)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [ ]:
print(M[0])
print(M[1])
print(M[2])


[1, 2, 3]
[4, 5, 6]
[7, 8, 9]


In [ ]:
print(M[0][0])
print(M[0][1])
print(M[0][2])

1
2
3


In [ ]:
print(M[0][0])
print(M[1][1])
print(M[2][2])

1
5
9


In [ ]:
print(M[0][2])
print(M[1][1])
print(M[2][0])

3
5
7


L4.3 Birthday Paradox

In [ ]:
import random
l=[]
l.append(random.random())
print(l)

l.append(random.random())
print(l)

[0.8325140455713607]
[0.8325140455713607, 0.3088902615127589]


In [ ]:
import random

l=[]

for i in range(10):
    l.append(random.random())
    print(l)

[0.641999818617312]
[0.641999818617312, 0.8035546785598672]
[0.641999818617312, 0.8035546785598672, 0.06528112982404644]
[0.641999818617312, 0.8035546785598672, 0.06528112982404644, 0.6656788676914944]
[0.641999818617312, 0.8035546785598672, 0.06528112982404644, 0.6656788676914944, 0.6857668539657413]
[0.641999818617312, 0.8035546785598672, 0.06528112982404644, 0.6656788676914944, 0.6857668539657413, 0.6092772203565112]
[0.641999818617312, 0.8035546785598672, 0.06528112982404644, 0.6656788676914944, 0.6857668539657413, 0.6092772203565112, 0.49986463611740073]
[0.641999818617312, 0.8035546785598672, 0.06528112982404644, 0.6656788676914944, 0.6857668539657413, 0.6092772203565112, 0.49986463611740073, 0.6002717118466251]
[0.641999818617312, 0.8035546785598672, 0.06528112982404644, 0.6656788676914944, 0.6857668539657413, 0.6092772203565112, 0.49986463611740073, 0.6002717118466251, 0.8065036938512197]
[0.641999818617312, 0.8035546785598672, 0.06528112982404644, 0.6656788676914944, 0.6857668

In [ ]:
import random

l=[]

for i in range(10):
    l.append(random.random())
print(l)

[0.1443571696996765, 0.6543355270855545, 0.5788329301433262, 0.6511042606806109, 0.6026720305788744, 0.7634612986785081, 0.0774485263293273, 0.3589169776332708, 0.06727788434432247, 0.30025755784191366]


In [ ]:
import random

l=[]
for i in range(10):
    l.append(random.randint(1,10))

    print(l)

[3]
[3, 4]
[3, 4, 7]
[3, 4, 7, 4]
[3, 4, 7, 4, 3]
[3, 4, 7, 4, 3, 2]
[3, 4, 7, 4, 3, 2, 6]
[3, 4, 7, 4, 3, 2, 6, 10]
[3, 4, 7, 4, 3, 2, 6, 10, 6]
[3, 4, 7, 4, 3, 2, 6, 10, 6, 7]


In [ ]:
import random

l=[]
for i in range(30):
    l.append(random.randint(1,365))
print(l)

[65, 191, 271, 29, 25, 233, 176, 74, 132, 255, 318, 9, 152, 239, 27, 288, 243, 233, 114, 189, 337, 12, 96, 77, 154, 64, 8, 266, 245, 358]


In [ ]:
l.sort()
print(l)

[8, 9, 12, 25, 27, 29, 64, 65, 74, 77, 96, 114, 132, 152, 154, 176, 189, 191, 233, 233, 239, 243, 245, 255, 266, 271, 288, 318, 337, 358]


In [ ]:
i = 0

while(i < len(l)-1):   # not til i <= len(l)-1
   if(l[i]==l[i+1]):
    print("Repeats")
   else:
    print("Don't repeat", l[i], l[i+1])

# researchers do use for to write papers , you can simulates how stock markets works,scientific simulation,simulates how covid spreads

In [ ]:
import random

l=[]
for i in range(50):
    l.append(random.randint(1,365))
l.sort
print(l)

i=0
flag = 0 #denotes that there is no repeation
while(i<len(l)-1):
     if(l[i]==l[i+1]):
        print('Repeat',l[i],l[i+1])
        flag=1
        break
     i=i+1
if(flag==0):
   print("No repeation")

[334, 132, 108, 130, 152, 330, 216, 102, 85, 184, 250, 155, 286, 96, 111, 293, 93, 89, 129, 73, 58, 285, 241, 283, 162, 109, 256, 300, 231, 172, 147, 332, 352, 7, 333, 110, 37, 219, 315, 323, 153, 275, 275, 318, 111, 54, 114, 212, 204, 142]
Repeat 275 275


L4.4  Naive Search in List

In [ ]:
l=[11,3,99,6,144,86]

import random
for i in range(10000):
    l.append(random.randint(1,1000000))
print(l)

[11, 3, 99, 6, 144, 86, 603996, 653781, 791345, 976472, 303526, 400986, 648023, 304563, 741750, 878189, 984195, 558152, 828887, 650418, 855484, 41637, 591104, 182575, 527583, 917680, 834310, 557117, 477858, 689742, 999564, 711376, 215037, 379269, 314688, 602586, 426888, 281609, 598335, 128485, 516451, 847, 445294, 884338, 789848, 156704, 556537, 661631, 372575, 714202, 702021, 474663, 107315, 708538, 298, 477442, 74901, 398201, 385326, 570334, 45289, 353921, 16999, 890564, 171702, 396242, 56192, 263315, 125701, 910632, 51997, 220181, 703326, 454361, 68953, 427809, 145109, 886635, 641719, 584831, 656097, 785709, 663737, 285230, 125613, 150717, 449822, 2513, 653880, 378869, 896844, 184508, 316722, 911655, 953237, 903409, 36613, 242500, 829316, 332621, 498488, 568442, 819558, 447893, 657551, 609321, 729189, 41454, 568176, 602162, 816888, 356090, 515660, 778696, 48301, 182678, 351567, 206314, 27255, 15542, 392290, 365767, 877859, 203818, 223160, 384585, 638930, 319927, 536036, 182038, 8951

In [ ]:
import random
l=[]
for i in range(100):
     l.append(random.randint(1,1000000))
print(l)

[307454, 687092, 514615, 936517, 737207, 670525, 156167, 368551, 411037, 219019, 485493, 642516, 396112, 184905, 822839, 566009, 867278, 732100, 389632, 626132, 354076, 856718, 274027, 227692, 618039, 770597, 868493, 92559, 392340, 950307, 183959, 624715, 607343, 621343, 150655, 341762, 827374, 634055, 706665, 817297, 735501, 497675, 286191, 928125, 795495, 24420, 679159, 533867, 24892, 601462, 857360, 381155, 82722, 817717, 812078, 176752, 573957, 235421, 65351, 981165, 453897, 922455, 775094, 999172, 638699, 252482, 913707, 244843, 960447, 776686, 198508, 741825, 201005, 539082, 729686, 108923, 541610, 492628, 526456, 659654, 824204, 347847, 199385, 554757, 943979, 613164, 377173, 395333, 693219, 504818, 512754, 746794, 113204, 727768, 444102, 335244, 449102, 619686, 552835, 161629]


In [ ]:
import random
l=[]
a=567172
for i in range(1000000):
  l.append(random.randint(1,1000000))

flag=0

for i in range(len(l)):
    if (a==l[i]):
        print('found')
        flag=1
        break;
if(flag==0):
   print("Not found")

found


In [ ]:
import random
l=[2001,1990,1985,2003,1988,1999]

n=0
while(n>-1):
   print("Enter a number,type -1 to exit:")
   n=int(input())

   flag=0

   for i in range(len(l)):
       if(n==l[i]):
           print("Wao,found")
           flag=1
           break;
   if(flag==0):
      print('Not found')

L4.5 The Obvious Sort

In [ ]:
l=[12,10,7,18,6,43,8,35]
l.sort()
print(l)

In [ ]:
l=[12,10,7,18,6,43,8,35]
x=[]

while(len(l)>0):
  min=l[0]
  for i in range(len(l)):
     if(l[i]<min):
        min=l[i]
  x.append(min)
  l.remove(min)

print(l)
print(x)

L4.6 Dot product

In [ ]:
l=[1,3,4,67,18,17]
sum=0
for i in range(len(l)):
  sum=sum+l[i]
print(sum)

110


In [ ]:
import random
l=random.sample(list(range(10000)),1000)
sum=0
for i in range(len(l)):
    sum=sum+l[i]
print(sum)

5064550


In [ ]:
import random
#write a piece of code to find the dot product
x=[1,7,3,4]
y=[8,6,3,2]
dot_product=(1*8)+(7*6)+(3*3)+(4*2)
print(dot_product)

67


In [ ]:
import random
x=[1,7,3,4]
y=[8,6,3,2]
sum=0
for i in range(len(x)):
  sum=sum+x[i]*y[i]

print(sum)

67


L4.7 Matrix Addition

In [ ]:
#Matrix by frist principles

dim=3

r1=[1,2,3]
r2=[4,5,6]
r3=[7,8,9]

s1=[1,2,1]
s2=[6,2,3]
s3=[4,2,1]

A=[]
A.append(r1)
A.append(r2)
A.append(r3)

B=[]
B.append(s1)
B.append(s2)
B.append(s3)

print(A)
print(B)

#i nee to add A and B

C=[[0,0,0],[0,0,0],[0,0,0]]
D=[[0,0,0],[0,0,0],[0,0,0]]

#C=[[],[],[]]
for i in range(dim):
    for j in range(dim):
      C[i][j]=A[i][j]+B[i][j]  #Matrix Addition
      D[i][j]=A[i][j]*B[i][j]   #Matrix Multiplication


print(C)
print(D)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1, 2, 1], [6, 2, 3], [4, 2, 1]]
[[2, 4, 4], [10, 7, 9], [11, 10, 10]]
[[1, 4, 3], [24, 10, 18], [28, 16, 9]]


L4.8-9| Matrix Multiplication 1 and 2

In [ ]:
r1=[1,2,3]
r2=[4,5,6]
r3=[7,8,9]

s1=[1,2,1]
s2=[6,2,3]
s3=[4,2,1]

A=[]
B=[]
A.append(r1)
A.append(r2)
A.append(r3)

B.append(s1)
B.append(s2)
B.append(s3)

C=[[0,0,0],[0,0,0],[0,0,0]]

dim=3

#C C[i][j] is the dot product of the ith row of A and the jth column of B

for i in range(dim):
    for j in range(dim):
            for k in range(dim):
               C[i][j] = C[i][j] + A[i][k]*B[k][j]

print(C)

# C[i][j]=dot product of A[i][....] and B[....][j]



[[25, 12, 10], [58, 30, 25], [91, 48, 40]]


In [ ]:
import numpy

A=[[1,2,3],[4,5,6],[7,8,9]]

B=[[1,2,1],[6,2,3],[4,2,1]]

X=numpy.mat(A)

Y=numpy.mat(B)

print(X*Y)

[[25 12 10]
 [58 30 25]
 [91 48 40]]


In [ ]:
import numpy as np
A

[[1, 2, 3], [4.5, 6], [7, 8, 9]]

In [ ]:
B

[[1, 2, 1], [6, 2, 3], [4, 2, 1]]

In [ ]:
X=numpy.mat(A)
Y=numpy.mat(B)
print(X*Y)

[[25 12 10]
 [58 30 25]
 [91 48 40]]
